tap "asmvik/formulae", "https://github.com/asmvik/homebrew-formulae.git"
tap "elevenlabs/tap"
tap "felixkratz/formulae"
tap "ngrok/ngrok"
tap "nikitabobko/tap"
tap "openclaw/tap"
tap "penso/tap"
tap "siddharthvaddem/openscreen"
tap "sleuth-io/tap"
tap "steipete/tap"
tap "supabase/tap"
brew "openssl@3", link: true
brew "bat"
brew "duckdb"
brew "espeak-ng"
brew "eza"
brew "xz"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "readline"
brew "googleworkspace-cli"
brew "sqlite"
brew "zstd"
brew "grip"
brew "herdr"
brew "ical-buddy"
brew "jq"
brew "lazygit"
brew "libb2"
brew "lua"
brew "lua@5.4"
brew "luarocks"
brew "mole"
brew "mosh"
brew "nmap"
brew "nvm"
brew "opencode"
brew "pandoc"
brew "pipx"
brew "pkgconf"
brew "poppler"
brew "pyenv"
brew "pyenv-virtualenv"
brew "railway"
brew "rclone"
brew "ruff"
brew "sf"
brew "sleepwatcher", restart_service: :changed
brew "starship"
brew "switchaudio-osx"
brew "tcl-tk@8"
brew "tmux"
brew "trash"
brew "uv"
brew "zlib"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "elevenlabs/tap/elevenlabs", trusted: true
brew "openclaw/tap/gogcli", trusted: true
brew "sleuth-io/tap/sx", trusted: true
cask "1password"
cask "nikitabobko/tap/aerospace", trusted: true
cask "bettermouse"
cask "bettertouchtool"
cask "bruno"
cask "chatgpt"
cask "codex"
cask "cursor"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "docker-desktop"
cask "figma"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "penso/tap/herdr-gpui", trusted: true
cask "homerow"
cask "itsycal"
cask "jordanbaird-ice"
cask "kando"
cask "loom"
cask "ngrok"
cask "notion"
cask "obsidian"
cask "openscreen"
cask "raycast"
cask "screen-studio"
cask "shottr"
cask "slack"
cask "spotify"
cask "stats"
cask "steam"
cask "tailscale-app"
cask "visual-studio-code"
cask "voiceink"
cask "whatsapp"
cask "zen"
cask "zoom"

# Installed by hand on the current Mac, but Homebrew has a cask for them
cask "bambu-studio"
cask "capcut"
cask "claude"
cask "conductor"
cask "darktable"
cask "granola"
cask "magicquit"
cask "quitter"
cask "roam"
cask "stremio"
cask "superset"
cask "tella"
cask "zo"

# No Homebrew cask. Install these by hand:
# Dropover, Fireflies, Hyprnote, Nicotine+, Paper (the design app), Photomator, Sand, Supercut
# Claude Code uses its native installer (~/.local/bin/claude), not the cask.
