require("items.apple")
require("items.menus")
require("items.yabai_mode")  -- yabai layout indicator (B/F/S)
require("items.spaces")  -- yabai spaces (use workspaces.lua for aerospace)
require("items.front_app")
require("items.calendar")
-- require("items.vpn")
require("items.widgets")
require("items.media")
