#!/bin/sh

# Reserve space for SketchyBar (height 40 at top)
# yabai -m config external_bar all:40:0

# Use BSP tiling layout
yabai -m config layout bsp

# Label spaces
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five

# Disable files from being managed by yabai
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Rippling$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^BetterTouchTool$" manage=off
yabai -m rule --add app="^BTT$" manage=off
yabai -m rule --add app="^Voiceink$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

yabai -m config window_placement second_child

# Rebalance the tree when windows change
yabai -m signal --add event=window_created  action="yabai -m space --balance"
yabai -m signal --add event=window_destroyed action="yabai -m space --balance"

# Send certain apps to specific labeled spaces (that you created with --label)
# Space 1
yabai -m rule --add app="^Google Chrome$"                 space=one
yabai -m rule --add app="^(zoom\.us|Zoom|Zoom Workplace)$" space=one

# Space 2
yabai -m rule --add app="^Slack$"                         space=two

# Space 3
yabai -m rule --add app="^Cursor$"                        space=three

# Space 4  (WhatsApp handled above with 2 rules)
yabai -m rule --add app="^(Zen|Zen Browser)$"             space=four
yabai -m rule --add app="^Messages$"                      space=four
yabai -m rule --add app="^Spotify$"                       space=four
yabai -m rule --add app="^WhatsApp$" space=four

# Space 5
yabai -m rule --add app="^Firefox$"                       space=five
 
# Padding and gaps
yabai -m config top_padding    0
yabai -m config bottom_padding 2
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

# after your labels, before or after the rules is fine
yabai -m signal --add event=window_created app=".*WhatsApp$" \
  action="yabai -m window --space four"

# Mouse modifier (hold fn + drag to move/resize)
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

pkill -x borders 2>/dev/null || true
borders active_color=0xff00ff00 inactive_color=0x00000000 width=6.0 style=round &
