require("items.widgets.granola")
require("items.widgets.meeting")
require("items.widgets.brew")
require("items.widgets.volume")
require("items.widgets.battery")
require("items.widgets.network")
require("items.widgets.ram")
require("items.widgets.cpu")
